//변수, 상수
//메모리에 저장한다. 읽어서 재사용. 변수.

// 변수의 5가지 주 개념
// 변수 이름 : 저장된 값의 고유 이름
// 변수 값 : 변수에 저장된 값
// 변수 할당 : 변수에 값을 저장하는 행위
// 변수 선언 : 변수를 사용하기 위해 컴퓨터에 알리는 행위
// 변수 참조 : 변수에 할당된 값을 읽어오는것

// 변수 선언 방법 3가지 : var , let , const
// 1. var
var myVar = "Hello World";
var myVar1 = "Test 1";
myVAR1 = "GoodBye"
// var 은 재할당, 재선언 모두 가능

// 2. let 
let myLet = "Hello World";
// let myLet1 = "Test 2";
myLet = "GoodBye 1";
// let은 재할당만 가능 재선언 x

// 3. const
const myConst = "Hello World2";
// const는 재할당 재선언 모두 불가능.
